"""Add station_id to consignors and consignees

Revision ID: 389c6071f83d
Revises: e876916215e1
Create Date: 2025-10-12 11:48:43.379996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389c6071f83d'
down_revision = 'e876916215e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stations', ['station_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stations', ['station_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_id')

    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
