"""Update pin code structure and consignor consignee fields

Revision ID: 978eeaca3f79
Revises: 389c6071f83d
Create Date: 2025-10-12 12:00:08.431095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '978eeaca3f79'
down_revision = '389c6071f83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code_id', sa.Integer(), nullable=True))
        batch_op.drop_index('uq_consignee_name_loc')
        batch_op.create_unique_constraint('uq_consignee_name_station', ['name', 'station_id'])
        batch_op.create_foreign_key(None, 'pin_codes', ['pin_code_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('state')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('city')

    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code_id', sa.Integer(), nullable=True))
        batch_op.drop_index('uq_consignor_name_loc')
        batch_op.create_unique_constraint('uq_consignor_name_station', ['name', 'station_id'])
        batch_op.create_foreign_key(None, 'pin_codes', ['pin_code_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('state')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('city')

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))

    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True))
        batch_op.add_column(sa.Column('pin_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_consignor_name_station', type_='unique')
        batch_op.create_index('uq_consignor_name_loc', ['name', 'city', 'state'], unique=True)
        batch_op.drop_column('pin_code_id')

    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True))
        batch_op.add_column(sa.Column('pin_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_consignee_name_station', type_='unique')
        batch_op.create_index('uq_consignee_name_loc', ['name', 'city', 'state'], unique=True)
        batch_op.drop_column('pin_code_id')

    # ### end Alembic commands ###
