"""add_consignor_consignee_agent_to_builty

Revision ID: b6c50de5cd04
Revises: add_rate_phonebook_agent_station
Create Date: 2025-10-13 10:41:48.179571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6c50de5cd04'
down_revision = 'add_rate_phonebook_agent_station'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consignor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consignor_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('consignee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consignee_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('booking_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'booking_agents', ['booking_agent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'consignors', ['consignor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'consignees', ['consignee_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True,
               existing_server_default=sa.text("'PARTY'"))

    with op.batch_alter_table('phone_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_book_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_book_entity_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False,
               existing_server_default=sa.text("'PARTY'"))

    with op.batch_alter_table('builty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_agent_id')
        batch_op.drop_column('consignee_phone')
        batch_op.drop_column('consignee_id')
        batch_op.drop_column('consignor_phone')
        batch_op.drop_column('consignor_id')

    # ### end Alembic commands ###
