"""add extended fields

Revision ID: e876916215e1
Revises: 1e6baa9b6f58
Create Date: 2025-10-08 19:59:42.872452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e876916215e1'
down_revision = '1e6baa9b6f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pin_code_text', sa.String(length=10), nullable=True))

    with op.batch_alter_table('booking_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))

    with op.batch_alter_table('builty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firm', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lr_no', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('eway_bill_no', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('goods_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('charged_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advance_amount', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'goods', ['goods_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('holiday_info', sa.Text(), nullable=True))

    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('holiday_info', sa.Text(), nullable=True))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rto', sa.String(length=64), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_pin_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('consignor_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('consignee_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('order_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('party', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pin_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stations', ['station_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_status', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('insurance_status')

    with op.batch_alter_table('pin_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('party')
        batch_op.drop_column('order_by')
        batch_op.drop_column('consignee_phone')
        batch_op.drop_column('consignor_phone')
        batch_op.drop_column('station_pin_code')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('rto')
        batch_op.drop_column('license_file')

    with op.batch_alter_table('consignors', schema=None) as batch_op:
        batch_op.drop_column('holiday_info')
        batch_op.drop_column('pin_code')

    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.drop_column('holiday_info')
        batch_op.drop_column('pin_code')

    with op.batch_alter_table('builty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('advance_amount')
        batch_op.drop_column('rate')
        batch_op.drop_column('charged_weight')
        batch_op.drop_column('actual_weight')
        batch_op.drop_column('goods_id')
        batch_op.drop_column('eway_bill_no')
        batch_op.drop_column('lr_no')
        batch_op.drop_column('firm')

    with op.batch_alter_table('booking_agents', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('pin_code_text')
        batch_op.drop_column('district')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
